// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyeebbafixacwhmlztzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5ZWViYmFmaXhhY3dobWx6dHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjA3OTIsImV4cCI6MjA3MTQzNjc5Mn0.GHXtcECZtN_NYq29wGzdLLaiqgvZVyu5DIo8Au8DEos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});